panels=panel1

[panel1]
plugins=fancymenu,taskbar,statusnotifier,tray,volume,worldclock,showdesktop
position=Bottom
desktop=0

[fancymenu]
type=fancymenu
alignment=Left
filterClear=true
autoSel=true
autoSelDelay=150

[taskbar]
type=taskbar
alignment=Left
buttonWidth=200
closeOnMiddleClick=true
groupingEnabled=false

[statusnotifier]
type=statusnotifier
alignment=Right

[tray]
type=tray
alignment=Right

[volume]
type=volume
alignment=Right
device=0

[worldclock]
type=worldclock
alignment=Right

[showdesktop]
type=showdesktop
alignment=Right
